server:
  port: 9000
spring:
  application:
    name: "cards"
  config:
    import:
      - "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
management:
  endpoints:
    web:
      exposure:
        include:
        - "refresh"
        - "busrefresh"