server:
  port: 8071
spring:
  application:
    name: "configserver"
  profiles:
    active:
    - git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/morettiale/proximagroup-micoservices-config.git"
          default-label: "main"
          timeout: 5
          clone-on-start: true
          force-pull: true
management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true